title: Kignuf, Freelance QA Engineer
theme: minima
author: GitHub User
description: > # this means to ignore newlines until "baseurl:"
  Kignuf, Freelance QA Engineer. Articles about cucumber, webdriverio, selenium, appium and more.

# social links
github_username: kignuf

show_excerpts: true # set to false to remove excerpts on the homepage
