title: Self help and unconventional wisdom for free minded people
theme: minima
author: Kevin Roulleau
description: > # this means to ignore newlines until "baseurl:"
  Kevin Roulleau, software developper. Articles about how to make sense of one's life, sharing personal experiences and exploring uncharted territories.

# social links
github_username: kignuf

show_excerpts: true # set to false to remove excerpts on the homepage
